name: 'Unit tests'
description: 'Runs the unit tests'
inputs:
  codecov_token:
    description: Codecov token
    required: true
runs:
  using: "composite"
  steps:
    - run: npx nx test graphql-mesh --parallel=3 --ci --code-coverage
      shell: bash

    - name: Codecov upload
      uses: codecov/codecov-action@v2
      with:
        token: ${{ inputs.codecov_token }}
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
