name: Publish to NPM
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build 🔧
        run: npm install && npx nx run graphql-mesh:build

      - name: Version
        shell: bash
        run: npx nx run graphql-mesh:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag last-release
        shell: bash
        run: |
          git tag -f last-release
          git push origin last-release --force

      - name: Publish package on NPM 📦
        run: npm publish ./dist/packages/graphql-mesh --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
